name: Calc App Build Pipeline

on:
  workflow_run:
    workflows: ["Calc App Unit Tests"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Frontend (React Build)
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975049962487:role/cas3135-ta-1-gha-role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Images
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO_BE: ${{ vars.ECR_REPOSITORY_BE }}
          REPO_FE: ${{ vars.ECR_REPOSITORY_FE }}
        run: |
          VERSION_TAG=$(date +'%Y%m%d-%H%M%S')
          
          IMAGE_URI_BE=$REGISTRY/$REPO_BE:$VERSION_TAG
          IMAGE_URI_FE=$REGISTRY/$REPO_FE:$VERSION_TAG
          
          # Backend 빌드 및 푸시
          docker build -t $IMAGE_URI_BE ./backend
          docker push $IMAGE_URI_BE
          
          # Frontend 빌드 및 푸시
          docker build -t $IMAGE_URI_FE ./frontend
          docker push $IMAGE_URI_FE
          
          echo "$IMAGE_URI_BE" > image_uri_be.txt
          echo "$IMAGE_URI_FE" > image_uri_fe.txt

      - name: Upload Image URI Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: image-uris
          path: |
            image_uri_be.txt
            image_uri_fe.txt
